### ISSUE TITLE
作者你好,可以提供一个验证码验证的demo吗,感觉在aspnetcore中没有什么好的方式来验证验证码

### ISSUE THREAD

**Issue by DUWENINK** [gebiWangshushu/Hei.Captcha#1]

**Comment by gebiWangshushu** [comment]
你好，我是直接生成的验证码的同时将验证码放到缓存里。
验证的时候取出来验证。
不知道问的是不是这个意思，缓存如果懒得封装可以直接使用 [EasyCaching](https://github.com/dotnetcore/EasyCaching)
