### ISSUE TITLE
中文泡泡验证码连续30次以上显示异常

### ISSUE THREAD

**Issue by iNuoers** [gebiWangshushu/Hei.Captcha#4]
中文泡泡验证码连续30次以上后，泡泡数逐步增多，最后只出现背景色了。

**Comment by gebiWangshushu** [comment]
感谢关注。抱歉未能几时回复；
可否告知具体重现步骤？比如你使用的版本，你是怎么调用的，贴下代码?
可参考Demo里面的用法再试试哦~

**Comment by gebiWangshushu** [comment]
没问题我就关闭了。

**Comment by iNuoers** [comment]
不好意思，忘记回复了。我后来重试了下，没发现问题了，非常感谢！
