### ISSUE TITLE
同一个SecurityCodeHelper实例，连续十几次获取之后中文验证码完全看不清楚。

### ISSUE THREAD

**Issue by fuyuesong** [gebiWangshushu/Hei.Captcha#5]
同一个SecurityCodeHelper实例多次生成验证码的时候会出现如下问题：

验证码1 中文泡泡验证码  连续十几次获取之后，再获取的验证码完全看不清楚，有N多圈圈甚至一片漆黑。

可以把Demo中的HomeController.cs头部改成如下代码，运行之后连续刷新十几次可测试出效果。

估计是有些变量没有释放不断叠加导致的。

`namespace Demo
{
    public class HomeController : Controller
    {
        static  SecurityCodeHelper _securityCode;

        public HomeController(SecurityCodeHelper securityCode)
        {
            if(_securityCode==null)
            _securityCode = securityCode;
        }
`

**Comment by gebiWangshushu** [comment]
感谢指出问题，不过我重现不了，能不能发下可以重现的demo给我看看~感谢

**Comment by fuyuesong** [comment]
你好，我把示例和录屏传到百度云了，您可以看看。
链接：https://pan.baidu.com/s/14DpUapKe_gsU4CU2G6D5jA 
提取码：47zf

**Comment by gebiWangshushu** [comment]
@fuyuesong 你好我看了的截屏，我发现你没按照demo来

```
 //原本是这样
 private readonly SecurityCodeHelper _securityCode;

//你改成了这样↓

 //连续刷新之后会变得非常卡
 static SecurityCodeHelper _securityCode;
```

**Comment by fuyuesong** [comment]
就是为了演示效果，所以改了代码演示给你看的。你可以对比一下，英文验证码多次刷新显示是正常的，中文验证码有问题，估计是中文验证码生成之后某些资源没有释放导致重复叠加。另外，一些通用类库或者方法根据实际需要定义全局静态是很正常的。

**Comment by gebiWangshushu** [comment]
@fuyuesong 你好，我按你那样改确实重现了，但 那是错误用法。SecurityCode是Scope的，不要搞成单例。

**Comment by gebiWangshushu** [comment]
错误用法，关闭了
